# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5df10800012b430f588575db4e3d006a06ec92b6ee2df5672c8a9f4b07ba966720eff692a42d4ed75a3c9c64127aa12a74d4bac07433515e2d37cd3997d65c23

test:
  secret_key_base: 7280dcb210a9299b225e06e646693c895c7d6bc3407a5bfa4d1b055b6185c098e560be69b22f0aab637330ff063cd891a5a5750e16b6f378766679a446ea551f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
