source 'https://rubygems.org'

gem 'rails', '4.2.6'

gem 'rails-api', '~>0.4', '>=0.4.0'

gem 'jbuilder', '~>2.0', '>=2.6.0'

gem 'pg', '~>0.19', '>=0.19.0'

gem 'thor', '0.19.1'

gem 'mongoid', '~>5.1', '>=5.1.5'

group :development do
  gem 'spring', '~>2.0', '>=2.0.0'
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
  gem 'rspec-rails', '~>3.5', '>=3.5.2'
end
