# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad6e7a928ef110817bb5576e3e95a531ea8b4a928aa67e567000caf310be3a762fdaed9f12043e14982142000441113c465c77d9b150923673ef3fd672a4ceef

test:
  secret_key_base: 297d7b291663b3ce960a61b92b7b9dcdcf3cf4c5ce937a8b14ea28062e748f12bb7b50525af89f211145d2597aab209166ecbeee473639ff411d91d077d44d21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
